version: "3.9"

services: 
  db:
    image: "mcr.microsoft.com/mssql/server:2019-latest"
    container_name: "db"
    environment:
      ACCEPT_EULA: "Y"
      SA_PASSWORD: "yourStrong(!)Password"
    ports:
      - "1433:1433"
    volumes:
      - db-volume:/var/opt/mssql

volumes: 
  db-volume: